package com.skillswap.notification;

public enum NotificationType {
	CONNECTION_REQUEST,
	CONNECTION_ACCEPTED,
	NEW_MESSAGE,
	SKILL_MATCH,
	SESSION_REQUEST,
	SESSION_ACCEPTED,
	SESSION_REJECTED,
	SESSION_CANCELLED,
	SESSION_COMPLETED,
	UPCOMING_SESSION,
	RATING_RECEIVED,
	REQUEST_RESPONSE,
	REQUEST_ACCEPTED,
	GROUP_INVITATION,
	GROUP_EVENT,
	CHALLENGE_REVIEW,
	BADGE_EARNED,
	CREDITS,
	SYSTEM
}
